# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=b'1987-04-27')),
                ('sex', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female'), (b'decline to identify', b'Decline to Identify')], default=b'decline to identify', max_length=50)),
                ('school_name', models.CharField(default=b'Eshkol Academy', max_length=50)),
                ('grade', models.CharField(choices=[(b'prek', b'Pre K'), (b'kindergarten', b'Kindergarten'), (b'first', b'First Grade'), (b'second', b'Second Grade'), (b'third', b'Third Grade'), (b'forth', b'Fourth Grade'), (b'fifth', b'Fifth Grade'), (b'sixth', b'Sixth Grade'), (b'seventh', b'Seventh Grade'), (b'eighth', b'Eighth Grade'), (b'ninth', b'Nineth Grade'), (b'tenth', b'Tenth Grade'), (b'eleventh', b'Eleventh Grade'), (b'twelfth', b'Twelfth Grade'), (b'adult', b'Adult')], default=b'prek', max_length=50)),
                ('address1', models.CharField(default=b'123 Fake St.', max_length=50)),
                ('address2', models.CharField(default=b'Apt 108', max_length=50)),
                ('city', models.CharField(default=b'New York', max_length=50)),
                ('state', models.CharField(default=b'New York', max_length=50)),
                ('zip_code', models.CharField(default=b'12345', max_length=5)),
                ('phone', models.CharField(default=b'9141234567', max_length=10)),
                ('email', models.EmailField(default=b'example@gmail.com', max_length=200)),
                ('volunteer_experience', models.TextField(default=b'Previous volunteer experience', max_length=5000)),
                ('interest_in_piano_village', models.TextField(default=b'I would like my child to learn how to play the piano', max_length=5000)),
                ('goals_for_service_to_the_community', models.TextField(default=b'', max_length=5000)),
                ('emergency_name', models.CharField(default=b'John Smith', max_length=10)),
                ('emergency_phone', models.CharField(default=b'9141234567', max_length=10)),
                ('relationship', models.CharField(default=b'Father', max_length=10)),
                ('how_did_you_hear_about_us', models.CharField(choices=[(b'friend', b'Friend'), (b'parent', b'Parent'), (b'website', b'Website'), (b'media', b'Media'), (b'other', b'Other')], default=b'media', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
